
apiVersion: v1
kind: ConfigMap
metadata:
  name: encontros-tech-config
data:
  APP_TITLE: "Encontros Tech"
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "8000"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "simple"
  SERVICE_NAME: "encontros-tech"
  SERVICE_VERSION: "1.0.0"
  PROMETHEUS_MULTIPROC_DIR: "/tmp/prometheus_multiproc"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: encontros-tech
  labels:
    app: encontros-tech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: encontros-tech
  template:
    metadata:
      labels:
        app: encontros-tech
    spec:
      containers:
      - name: encontros-tech
        image: gabrielcayres/bootcamp-encontros-tech:v1
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: encontros-tech-secret
              key: database-url
        envFrom:
        - configMapRef:
            name: encontros-tech-config
---
apiVersion: v1
kind: Service
metadata:
  name: encontros-tech
  labels:
    app: encontros-tech
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: encontros-tech
