apiVersion: v1
kind: Secret
metadata:
  name: encontros-tech-secret
type: Opaque
stringData:
  database-url: "postgresql://doadmin:AVNS_CE9P-aoE7jr3lxNg8jn@private-db-postgresql-nyc1-21167-do-user-10478846-0.e.db.ondigitalocean.com:25060/defaultdb?sslmode=require"