name: Conversao Distancia CI-CD
on:
  push:
    branches: [ "main" ]
    paths: 
      - '01-conversao-distancia/**'
  workflow_dispatch:

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              
            - uses: actions/setup-python@v6
              with:
                python-version: '3.11' 
                
            - name: Install Dependencies
              working-directory: 01-conversao-distancia
              run: |
                python -m pip install --upgrade pip 
                pip install -r requirements.txt

            - name: Build and Push Docker Image
              uses: ./.github/actions/docker-build
              with:
                dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
                dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
                image-name: fabricioveronez/bootcamp-conversao-distancia
                dockerfile-path: ./01-conversao-distancia/Dockerfile
                context-path: ./01-conversao-distancia
                tag: v${{ github.run_number }}

    CD:
        runs-on: ubuntu-latest
        needs: [CI]
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              
            - name: Deploy to Kubernetes
              uses: ./.github/actions/k8s-deploy
              with:
                kubeconfig: ${{ secrets.KUBECONFIG }}
                manifest-path: 01-conversao-distancia/k8s/manifesto.yaml
                image-name: fabricioveronez/bootcamp-conversao-distancia
                image-tag: v${{ github.run_number }}